name: First Interaction

on:
  pull_request:
  issue:

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening this Issue! We'll give you a return ASAP 🚀'
        pr-message: 'Thank you for opening this Pull Request! We'll give you a return ASAP 🚀'
